import os
from pathlib import Path

# QEPC Project Structure Definition
# Keys are directories, Values are lists of filenames to create inside them
structure = {
    "qepc": ["__init__.py"],
    "qepc/autoload": ["__init__.py", "qepc_autoload.py", "paths.py"],
    "qepc/core": ["__init__.py", "scripts.py", "lambda_engine.py", "simulator.py", "model_config.py"],
    "qepc/sports": ["__init__.py"],
    "qepc/sports/nba": ["__init__.py", "lineups.py", "props.py", "props_adjust.py", "sim.py"],
    "qepc/sports/nfl": ["__init__.py", "lineups.py", "props.py", "lambda_engine.py", "sim.py"],
    "qepc/sports/nhl": ["__init__.py", "sim.py"],
    "qepc/utils": ["__init__.py", "time_utils.py", "data_cleaning.py", "diff_evaluator.py", "logger.py", "backup.py"],
    "qepc/ui": ["__init__.py", "banners.py", "colors.py", "menu.py", "progress.py"],
    "data": [],
    "data/metadata": ["teams.json", "arenas.csv", "league_settings.json"],
    "data/cache": ["lineup_cache.json", "props_cache.json"],
    "data/backups": [],
    "notebooks": ["QEPC_Main.ipynb", "Dev_Sandbox.ipynb", "Backtests.ipynb", "ScheduleInspector.ipynb"],
    "scripts": ["bootstrap.py", "rebuild_from_backup.py"],
    "tests": ["test_autoload.py", "test_lambda_engine.py", "test_schedule_integrity.py"],
}

# Root level files
root_files = ["README.md", "requirements.txt", ".gitignore"]

def create_structure():
    base_path = Path.cwd()
    print(f"🚀 Initializing QEPC Deluxe Structure in: {base_path}")

    # Create Directories and Sub-files
    for folder, files in structure.items():
        dir_path = base_path / folder
        dir_path.mkdir(parents=True, exist_ok=True)
        print(f"   📁 Created: {folder}/")
        
        for file in files:
            file_path = dir_path / file
            if not file_path.exists():
                # Create empty file or basic signature
                with open(file_path, 'w', encoding='utf-8') as f:
                    if file.endswith(".py"):
                        f.write(f'"""\nQEPC Module: {file}\nGenerated by Bootstrap\n"""\n\n')
                    elif file.endswith(".ipynb"):
                        f.write('{"cells": [], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}')
                    else:
                        f.write("")
                # print(f"      📄 {file}")

    # Create Root Files
    for rf in root_files:
        (base_path / rf).touch()
        print(f"   📄 {rf}")

    # Create a shim for qepc_autoload in the root so 'import qepc_autoload' works easily
    shim_code = """
import sys
from pathlib import Path

# Add project root to path
root = Path(__file__).parent
if str(root) not in sys.path:
    sys.path.append(str(root))

# Import the actual autoloader from the package
try:
    from qepc.autoload.qepc_autoload import *
    print("[QEPC] Root Shim Loaded. Forwarding to qepc.autoload...")
except ImportError as e:
    print(f"[QEPC] Error loading internal autoloader: {e}")
"""
    with open(base_path / "qepc_autoload.py", "w") as f:
        f.write(shim_code)
    print("   ⚡ Created root shim: qepc_autoload.py")

    # Create Data Placeholder
    games_csv = base_path / "data" / "Games.csv"
    if not games_csv.exists():
        with open(games_csv, "w") as f:
            f.write("Date,Time,Away Team,Home Team,Venue,Notes\n")
        print("   📊 Created placeholder data/Games.csv")

    print("\n✅ QEPC Bootstrap complete. Ready for code injection.")

if __name__ == "__main__":
    create_structure()