"""
-QEPC Module: test_lambda_engine.py
-Generated by Bootstrap
-"""
+import pytest
 
+pandas = pytest.importorskip("pandas")
+
+from qepc.core.lambda_engine import compute_lambda
+
+
+def test_compute_lambda_uses_defensive_average():
+    schedule = pandas.DataFrame(
+        {
+            "Home Team": ["Alpha"],
+            "Away Team": ["Beta"],
+        }
+    )
+
+    team_stats = pandas.DataFrame(
+        {
+            "Team": ["Alpha", "Beta"],
+            "ORtg": [110.0, 100.0],
+            "DRtg": [90.0, 110.0],
+            "Pace": [100.0, 100.0],
+            "Volatility": [12.0, 12.0],
+        }
+    )
+
+    result = compute_lambda(schedule, team_stats)
+
+    expected_lambda_home = 110.0 * (110.0 / 105.0) * (110.0 / 100.0) * 1.0 * 1.028
+    expected_lambda_away = 110.0 * (100.0 / 105.0) * (90.0 / 100.0) * 1.0
+
+    assert result.loc[0, "lambda_home"] == pytest.approx(expected_lambda_home)
+    assert result.loc[0, "lambda_away"] == pytest.approx(expected_lambda_away)
